<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Umbraco.Community.Licensing.Core.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="[18.10.1]" />
    <PackageReference Include="xunit.runner.visualstudio" Version="[4.0.0]" />
    <PackageReference Include="xunit.v3" Version="[4.0.1]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Umbraco.Community.Licensing.Core\Umbraco.Community.Licensing.Core.csproj" />
  </ItemGroup>

</Project>
